include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - always_use_package_imports
    - avoid_print
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
