import 'package:flutter/material.dart';

class IconMapper {
  static const Map<String, IconData> _map = {
    // Finanças
    'money': Icons.attach_money,
    'payments': Icons.payments,
    'account_balance': Icons.account_balance,
    'account_balance_wallet': Icons.account_balance_wallet,
    'savings': Icons.savings,
    'credit_card': Icons.credit_card,
    'receipt': Icons.receipt,
    'receipt_long': Icons.receipt_long,
    'trending_up': Icons.trending_up,
    'trending_down': Icons.trending_down,
    'pie_chart': Icons.pie_chart,
    'bar_chart': Icons.bar_chart,
    'currency_exchange': Icons.currency_exchange,
    'swap_horiz': Icons.swap_horiz,
    'wallet': Icons.wallet,
    'local_atm': Icons.local_atm,
    // Casa
    'home': Icons.home,
    'house': Icons.house,
    'apartment': Icons.apartment,
    'bed': Icons.bed,
    'kitchen': Icons.kitchen,
    'chair': Icons.chair,
    'cleaning_services': Icons.cleaning_services,
    'water_drop': Icons.water_drop,
    'bolt': Icons.bolt,
    'wifi': Icons.wifi,
    'tv': Icons.tv,
    'phone_android': Icons.phone_android,
    'computer': Icons.computer,
    // Alimentação
    'restaurant': Icons.restaurant,
    'local_pizza': Icons.local_pizza,
    'local_cafe': Icons.local_cafe,
    'local_bar': Icons.local_bar,
    'fastfood': Icons.fastfood,
    'bakery_dining': Icons.bakery_dining,
    'lunch_dining': Icons.lunch_dining,
    'dinner_dining': Icons.dinner_dining,
    'local_grocery_store': Icons.local_grocery_store,
    'shopping_cart': Icons.shopping_cart,
    'grocery': Icons.local_grocery_store,
    // Transporte
    'directions_car': Icons.directions_car,
    'directions_bus': Icons.directions_bus,
    'directions_subway': Icons.directions_subway,
    'directions_bike': Icons.directions_bike,
    'flight': Icons.flight,
    'train': Icons.train,
    'local_taxi': Icons.local_taxi,
    'two_wheeler': Icons.two_wheeler,
    'local_gas_station': Icons.local_gas_station,
    'electric_car': Icons.electric_car,
    // Saúde
    'favorite': Icons.favorite,
    'local_hospital': Icons.local_hospital,
    'medical_services': Icons.medical_services,
    'medication': Icons.medication,
    'fitness_center': Icons.fitness_center,
    'spa': Icons.spa,
    'health_and_safety': Icons.health_and_safety,
    'psychology': Icons.psychology,
    // Educação
    'school': Icons.school,
    'menu_book': Icons.menu_book,
    'local_library': Icons.local_library,
    'science': Icons.science,
    'calculate': Icons.calculate,
    'laptop': Icons.laptop,
    'headphones': Icons.headphones,
    'create': Icons.create,
    // Lazer
    'movie': Icons.movie,
    'sports_soccer': Icons.sports_soccer,
    'sports_esports': Icons.sports_esports,
    'music_note': Icons.music_note,
    'theater_comedy': Icons.theater_comedy,
    'beach_access': Icons.beach_access,
    'hiking': Icons.hiking,
    'camera_alt': Icons.camera_alt,
    'pool': Icons.pool,
    // Vestuário
    'checkroom': Icons.checkroom,
    'shopping_bag': Icons.shopping_bag,
    'watch': Icons.watch,
    'dry_cleaning': Icons.dry_cleaning,
    // Trabalho
    'work': Icons.work,
    'business': Icons.business,
    'business_center': Icons.business_center,
    'meeting_room': Icons.meeting_room,
    'print': Icons.print,
    // Pessoas
    'people': Icons.people,
    'person': Icons.person,
    'family_restroom': Icons.family_restroom,
    'child_care': Icons.child_care,
    'pets': Icons.pets,
    // Especial
    'card_giftcard': Icons.card_giftcard,
    'cake': Icons.cake,
    'celebration': Icons.celebration,
    'redeem': Icons.redeem,
    'church': Icons.church,
    'volunteer_activism': Icons.volunteer_activism,
    // Outros
    'category': Icons.category,
    'star': Icons.star,
    'flag': Icons.flag,
    'label': Icons.label,
    'bookmark': Icons.bookmark,
    'settings': Icons.settings,
    'security': Icons.security,
    'public': Icons.public,
    'build': Icons.build,
    'handshake': Icons.handshake,
    'help': Icons.help,
    'info': Icons.info,
  };

  static IconData fromString(String name) => _map[name] ?? Icons.category;

  static Map<String, IconData> get all => _map;

  static Map<String, List<MapEntry<String, IconData>>> get categorized => {
    'Finanças': _entries([
      'money',
      'payments',
      'account_balance',
      'account_balance_wallet',
      'savings',
      'credit_card',
      'receipt',
      'receipt_long',
      'trending_up',
      'trending_down',
      'pie_chart',
      'bar_chart',
      'currency_exchange',
      'swap_horiz',
      'wallet',
      'local_atm',
    ]),
    'Casa': _entries([
      'home',
      'house',
      'apartment',
      'bed',
      'kitchen',
      'chair',
      'cleaning_services',
      'water_drop',
      'bolt',
      'wifi',
      'tv',
      'phone_android',
      'computer',
    ]),
    'Alimentação': _entries([
      'restaurant',
      'local_pizza',
      'local_cafe',
      'local_bar',
      'fastfood',
      'bakery_dining',
      'lunch_dining',
      'dinner_dining',
      'local_grocery_store',
      'shopping_cart',
    ]),
    'Transporte': _entries([
      'directions_car',
      'directions_bus',
      'directions_subway',
      'directions_bike',
      'flight',
      'train',
      'local_taxi',
      'two_wheeler',
      'local_gas_station',
      'electric_car',
    ]),
    'Saúde': _entries([
      'favorite',
      'local_hospital',
      'medical_services',
      'medication',
      'fitness_center',
      'spa',
      'health_and_safety',
      'psychology',
    ]),
    'Educação': _entries([
      'school',
      'menu_book',
      'local_library',
      'science',
      'calculate',
      'laptop',
      'headphones',
      'create',
    ]),
    'Lazer': _entries([
      'movie',
      'sports_soccer',
      'sports_esports',
      'music_note',
      'theater_comedy',
      'beach_access',
      'hiking',
      'camera_alt',
      'pool',
    ]),
    'Vestuário': _entries([
      'checkroom',
      'shopping_bag',
      'watch',
      'dry_cleaning',
    ]),
    'Trabalho': _entries([
      'work',
      'business',
      'business_center',
      'meeting_room',
      'print',
    ]),
    'Pessoas': _entries([
      'people',
      'person',
      'family_restroom',
      'child_care',
      'pets',
    ]),
    'Especial': _entries([
      'card_giftcard',
      'cake',
      'celebration',
      'redeem',
      'church',
      'volunteer_activism',
    ]),
    'Outros': _entries([
      'category',
      'star',
      'flag',
      'label',
      'bookmark',
      'settings',
      'security',
      'public',
      'build',
      'handshake',
      'help',
    ]),
  };

  static List<MapEntry<String, IconData>> _entries(List<String> keys) =>
      keys.map((k) => MapEntry(k, _map[k] ?? Icons.category)).toList();
}
